import Head from "next/head";
import Navbar from "../../components/Navbar";
import ProjectPreview from "../../components/ProjectPreview";
import Github from "../../public/github.svg";
import Instagram from "../../public/instagram.svg";
import Mail from "../../public/mail.svg";
import Twitter from "../../public/twitter.svg";
import Linkedin from "../../public/linkedin.svg";
import SocialButton from "../../components/SocialButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Riyaz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
  <div className="bg-zinc-200 h-[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover">
    <h1 className="text-4xl font-semibold">
      Hello, I'm a Web and App Developer with 3 years of experience in Web development and 1 year in App development.
    </h1>
    <p className="flex-1">
      I'm passionate about crafting seamless digital experiences and thrive on creating efficient, user-friendly solutions for both web and mobile platforms.
    </p>
    <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
      <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">
        Contact me
      </button>
      <div className="flex items-center gap-4">
        <a href="https://github.com/Riyaz1203" target="_blank" rel="noopener noreferrer">
          <SocialButton bgColor="github">
            <Github className="w-5 h-5" /> {/* Replace with GitHub logo */}
          </SocialButton>
        </a>
        <a href="mailto:mohammedriyaz12032003@gmail.com">
    <SocialButton bgColor="mail">
      <Mail className="w-5 h-5" />
    </SocialButton>
  </a>
        <a href="www.linkedin.com/in/mohammed--riyaz" target="_blank" rel="noopener noreferrer">
          <SocialButton bgColor="linkedin">
            <Linkedin className="w-5 h-5" />
          </SocialButton>
        </a>
        
        <a href="https://www.instagram.com/md.riyazz_/" target="_blank" rel="noopener noreferrer">
          <SocialButton bgColor="instagram">
            <Instagram className="w-5 h-5" />
          </SocialButton>
        </a>
        <a href="tel:+919629158073" target="_blank" rel="noopener noreferrer">
          <SocialButton bgColor="twitter">
            <Twitter className="w-5 h-5" />
          </SocialButton>
        </a>
      </div>
    </div>
  </div>
  <div className="h-[30rem] rounded-3xl p-8 bg-[url('/profile.jpg')] bg-cover bg-center" />
</section>


      <section id="projects" className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
        <ProjectPreview
          name="Flip App"
          description="Next-gen social media"
          imageUrl="/project-1.png"
          bgColor="#685cdd"
          dark
        />
        <ProjectPreview
          name="Moneyscape"
          description="Lend and borrow dashboard"
          imageUrl="/project-2.png"
          bgColor="#313442"
          dark
        />
        <ProjectPreview
          name="Admin Onboarding"
          description="Increase user engagement"
          imageUrl="/project-3.png"
        />
        <ProjectPreview
          name="Project Dashboard"
          description="Project management app"
          bgColor="#4e4e56"
          dark
        />
        <ProjectPreview
          name="Newsy App"
          description="News aggregator app"
          imageUrl="/project-2.png"
          bgColor="#171717"
          dark
        />
        <ProjectPreview
          name="Krypto"
          description="Analyze crypto currency"
          imageUrl="/project-3.png"
        />
      </section>
      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        <div className="bg-zinc-200 h-[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover">
          <h1 className="text-4xl font-semibold">
          Hello, I'm a Web and App Developer with 3 years of experience in Web development and 1 year in App development.
          </h1>
          <p className="flex-1">
          I'm passionate about crafting seamless digital experiences and thrive on creating efficient, user-friendly solutions for both web and mobile platforms.

          </p>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">
              Contact me
            </button>
            <div className="flex items-center gap-4">
              <SocialButton bgColor="github">
                <Github className="w-5 h-5" />
              </SocialButton>
              <SocialButton bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
            </div>
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl p-8 bg-[url('/profile.jpg')] bg-cover bg-center" />
      </section>
    </>
  );
}
